### ISSUE TITLE
Testing for v1.0.5

### ISSUE THREAD

**Issue by BurningTreeC** [flancast90/Speech-To-Text-in-TW5#10]
We should now test test test so that we can release v1.0.5

- Is language switching stable (by all 3 methods)?
- Do user-defined voice commands work consistently?
- Do user-defined keywords work consistently?

**Comment by BurningTreeC** [comment]
... and should we test anything else?

**Comment by flancast90** [comment]
I think we should test everything you said, and maybe add some more similar
words that might be helpful towards reducing inconsistency.

I think, that before v1.0.5, we should also add the editor toolbar
options/button for transcription directly into that open tiddler.

**Comment by BurningTreeC** [comment]
Hi @flancast90 , the editor toolbar button is a lot of work... Maybe more than we've done until now. I don't think we'll be able to add it to v1.0.5

**Comment by flancast90** [comment]
Oh ok, no problem. I didn’t realize it was that much work. I’ll go ahead
and do some tests on my end, and you can do the same for yours.

As needed, we’ll add the similar-sounding words (I can imagine there will
be quite a few for Tiddler).

**Comment by BurningTreeC** [comment]
@flancast90 - why would we want to add words for Tiddler?

**Comment by flancast90** [comment]
My mistake, @BurningTreeC, I was a bit confused about the user-defined
command “New Tiddler” on the demo. I now see that, since it is user
defined, they can add more words that invoke the action.

**Comment by BurningTreeC** [comment]
Hi @flancast90 I have now found some bugs about user-defined commands and fixed them
I've also made it possible that languages that don't have spaces between words, like chinese, can trigger commands

**Comment by BurningTreeC** [comment]
... but somehow we should test the latter ... I don't speak chinese :grinning:

**Comment by flancast90** [comment]
Neither do I. Maybe just the text-to-speech on Google Translate will do it?

**Comment by BurningTreeC** [comment]
Ok @flancast90 - I've finished testing on my side.

Do you want to create the new Release?

**Comment by flancast90** [comment]
I'll do it!

**Comment by flancast90** [comment]
Closing because v1.5.0 out!
