### ISSUE TITLE
Help needed in fixing the double-execution of commands

### ISSUE THREAD

**Issue by BurningTreeC** [flancast90/Speech-To-Text-in-TW5#11]
The `getTranscriptCommands` function executes commands
There's a logical error somewhere which causes commands being executed twice

I need help in solving this problem

**Comment by BurningTreeC** [comment]
To reproduce the issue:

```
Ok Wiki Ok Wiki sidebar
```

The sidebar doesn't move but in fact it's opened and closed (closed and opened) at the same time

**Comment by flancast90** [comment]
Ok. I’ll take a look on my end later today. It’s probably some simple JS we
both missed.

**Comment by BurningTreeC** [comment]
I believe it's fixed now @flancast90 :smile_cat:
