### ISSUE TITLE
Text-editor toolbar button brainstorming

### ISSUE THREAD

**Issue by BurningTreeC** [flancast90/Speech-To-Text-in-TW5#14]
I open this issue as a reminder that we want to create a text-editor toolbar button that allows inserting the recorded text into the current tiddlers' text field

For that we need some brainstorming and we need to collect information about the tiddlywiki internals so that we know how we can realize this

**Comment by flancast90** [comment]
OK, @BurningTreeC, sounds great! As a side question, where do you find info on this TW integration? I can't seem to find anything on the web related to TW plugin-making.

If there is  way to get the currently active/open tiddler, we could just use the normal function, with just the location changed to append the transcript. I'll leave the TW-research mainly to you, and work on re-factoring our location calls to a new function which takes various args to determine where to place them.

**Comment by BurningTreeC** [comment]
Hi @flancast90 , I look at tiddlywiki.com and look at the tiddlers tagged $:/tags/EditorToolbar
They dispatch messages of type `tm-edit-text-operation` which are handled of the surrounding text-editor (see `$:/core/modules/editor/factory.js`)
I think we somehow need to create a new text-operation (see all tiddlers with the field module-type of value texteditoroperation)
That textoperation should be dispatched when recording stops and it should insert its text at the editors' caret-position

**Comment by BurningTreeC** [comment]
@flancast90 I've now [opened a discussion](https://github.com/Jermolene/TiddlyWiki5/discussions/5957) over at the TiddlyWiki5 repository where I hope that we get some help

**Comment by BurningTreeC** [comment]
In the current v1.0.6-alpha it's possible to pipe the transcript into inputs and textareas
I believe that makes the toolbar button obsolete

**Comment by flancast90** [comment]
I saw! Really Cool! I agree with you that we don’t need the editor toolbar
anymore, too. Anything I can do in the code?

Recently I haven’t been as active in that repo, since I’ve been split
working on other TW tools and school, but I can find time to do something.

**Comment by BurningTreeC** [comment]
@flancast90 I have fixed a bug with the codemirror text editor and if we don't get any bug reports we could release version 1.0.6 (and close this issue)

**Comment by BurningTreeC** [comment]
@flancast90 , should we release v1.0.6 ?

**Comment by flancast90** [comment]
Sure, I didn't experience issues on my end on the demo page, and everything looks great! You did most of the work in this release (and the last 2-3), so you can have the honour of telling the group about it. 

I hope to be able to integrate TW-sounds in the plugin soon; TW-Sounds is nearing completion!

**Comment by BurningTreeC** [comment]
Looking forward to TW-sounds, I'm very curious what you make about it :+1:
