### ISSUE TITLE
Made my first solo plugin!

### ISSUE THREAD

**Issue by flancast90** [flancast90/Speech-To-Text-in-TW5#15]
@BurningTreeC:

I just wanted to thank you for all the help you've been so far in how to make a TW-plugin, and wanted to announce that I've made my first solo plugin: text-to-speech. The plugin is really quite simple, and I got the idea from TiddlyTweeter's question about this functionality. I felt that it wouldn't fit this plugin well (a bit off-topic for this plugin), so I created a minimal implementation of something [here](https://github.com/flancast90/text-to-speech-in-tw5).

**Comment by BurningTreeC** [comment]
Congratulations @flancast90 😊

**Comment by BurningTreeC** [comment]
@flancast90 I've seen that in your new plugin you export the name of the startup module as "speech-to-text" and I don't know if that doesn't clash with the name of the speech-to-text plugin, which is also "speech-to-text". I believe that you should change that name to "text-to-speak" or whatever you like

**Comment by flancast90** [comment]
Whoops! I used the file structure of this plugin there, and must have forgotten to rename something! Thanks for the catch!
