### ISSUE TITLE
We should make it clear that this plugin works best on Chrome/Chromium + under NodeJs

### ISSUE THREAD

**Issue by BurningTreeC** [flancast90/Speech-To-Text-in-TW5#16]
As the title implies, we should make it clear that this plugin works best on Chrome/Chromium and under NodeJs

What makes it work best under NodeJs is the granting of permissions for microphone access
Chrome/Chromium can permanently allow microphone access to websites using the `https` protocol but not to local files ( `file:///` )

**Comment by flancast90** [comment]
Ok. What do you recommend we do besides just say it in the README?
