### ISSUE TITLE
Toolbar and Commands

### ISSUE THREAD

**Issue by flancast90** [flancast90/Speech-To-Text-in-TW5#3]
As requested, I have opened a new discussion for the implementation of the feedback received. I intend to elaborate more on the command keywords, as well.

**Comment by BurningTreeC** [comment]
Hi @flancast90 , what we could do is let users create tiddlers tagged with `$:/tags/VoiceCommand`, let them add a field `voice-command` with the corresponding text that should invoke the action and in the text field they can write the action which should be invoked

**Comment by flancast90** [comment]
That's a good idea! What if we just add some kind of ``$:/config/VoiceCommands`` tiddler, with some input fields and a button to add a new field onclick. The input fields would define the input (words), as well as the code/action the words will invoke. 

At runtime, the program can listen for 'Ok Wiki', and then detect if what comes after that is defined in one of the fields. If it is, it can run the code in the input next to it (store the number of the input with data-id or similar, possibly). If you can have the program create this tiddler (if it doesn't exist already in the user's wiki), and give me some way to grab the inputs (by id or some other method), I can do the rest!

**Comment by BurningTreeC** [comment]
I'm one step ahead @flancast90 - see #7

**Comment by flancast90** [comment]
Pasta Macaroni Sidebar Question: just tested this, and nothing seems to happen. Is this intended? What is supposed to happen?

**Comment by BurningTreeC** [comment]
:grin: when nothing happens then it did not recognize one of the words correctly
the sidebar should toggle open/closed

**Comment by BurningTreeC** [comment]
Did you get a resulting transcript tiddler @flancast90 ?

**Comment by BurningTreeC** [comment]
I just made "Pasta" an alias for "Ok" and "Macaroni" an alias for "Wiki" (not within the JS code, user-side) ... and a user-defined action that is triggered by "Sidebar"

**Comment by flancast90** [comment]
No. I did not get a transcript. A few times, it found incorrect words,
which it then gave in a transcript, but the two times I got it right, I got
no transcript and the Mic ended.

**Comment by BurningTreeC** [comment]
That's strange @flancast90 , on my side it's working fine. Does "Ok Wiki Sidebar" work for you?

**Comment by BurningTreeC** [comment]
We'll probably re-add some console logs and see their outputs

**Comment by flancast90** [comment]
Well I can't even test it now :) The thing either thinks: wiki is Nikki (got wiki as Google once, too), or Sidebar is: divebar, Side Bar, etc.

**Comment by BurningTreeC** [comment]
You can use the tiddler $:/config/speech-to-text/keywords and add "Nikki" to the field `wiki-keywords`
And you can use the tiddler $:/VoiceCommands/toggle-sidebar and add "divebar" and "[[Side Bar]]" to its `voice-commands` field

**Comment by flancast90** [comment]
OK Wiki Sidebar works, just had to refresh and move my phone away from my laptop Mic. I'd assume the closeness of the devices was causing the Mic signal and my voice to be distorted to the program. Probably worth mentioning in the documentation, too.

**Comment by flancast90** [comment]
Worth noting, too, that side bar is recognized as salad bar 75% of the time. Is that easy enough to add to the JS right now, as with Wiki? Or does it need new code for that?

**Comment by BurningTreeC** [comment]
>Worth noting, too, that side bar is recognized as salad bar 75% of the time. Is that easy enough to add to the JS right now, as with Wiki? Or does it need new code for that?

Yes :grin: that happened to me, too

You'll have to understand the user-voice-command mechanism which is done in WikiText only

**Comment by BurningTreeC** [comment]
`Sidebar` is a custom user command
It's in a tiddler tagged `$:/tags/VoiceCommand`
The JS side filters all tiddlers tagged so and stores whatever is in their `voice-commands` field in an array. What's in the text field is stored in another array (the actions that should get triggered when one of the voice commands from the `voice-commands` field is detected)

**Comment by flancast90** [comment]
Just realized I might have made a stupid mistake. The language was in
English UK. It may have trouble for me because my accent is American. I’ll
run more test for this, but it might be a facepalm moment for me.

**Comment by BurningTreeC** [comment]
I'll close this issue and create a new one for the text-editor toolbar button only
