### ISSUE TITLE
User - defined actions and keywords

### ISSUE THREAD

**Issue by BurningTreeC** [flancast90/Speech-To-Text-in-TW5#7]
In the current master we can create tiddlers with tag `$:/tags/VoiceCommand` and the field `voice-command` which contains the command that should trigger the action. The text field should contain the actions that are then triggered.

There's also the possibility to define your own custom keywords additionally to `Ok` and `Wiki` using the tiddler `$:/config/speech-to-text/keywords` and its fields `ok-keywords` and `wiki-keywords`

The field `ok-keywords` could then contain "Pasta pasta" and the field `wiki-keywords` could contain "Maccheroni macaroni" and then `Pasta macaroni switch language to german` would work

**Comment by BurningTreeC** [comment]
Why I'm using the method with tagging tiddlers with `$:/tags/VoiceCommand` is because the keyboard-shortcut mechanism uses the same model and users know how to work with this

**Comment by flancast90** [comment]
Awesome! Anything you want me to do? In the meantime, I'll start the other repo for letter sounds.

**Comment by BurningTreeC** [comment]
Yes, if you want you could work on #8

**Comment by BurningTreeC** [comment]
I think we can close this issue since it's implemented
