### ISSUE TITLE
Users may want that listening never stops unless they stop it by hand or command

### ISSUE THREAD

**Issue by BurningTreeC** [flancast90/Speech-To-Text-in-TW5#8]
We could add a config which, if set to `yes` restarts the recognition automatically when it would end by timeout. Then it would only stop if it's stopped by hand via button-click or keyboard shortcut or via voice-command `stop listening`

**Comment by BurningTreeC** [comment]
I've already implemented this :+1:

**Comment by flancast90** [comment]
I was thinking of a similar idea. Maybe just some sort of selection that does it?

Was also wondering if you could share some code to get the current language of TW (not the plugin), TW itself.

**Comment by BurningTreeC** [comment]
@flancast90 , you can always get the text of a tiddler by `$tw.wiki.getTiddlerText("title of tiddler");`
Then it's a question in which tiddler tiddlywiki stores the language
