### ISSUE TITLE
Get Current Lang of TW 

### ISSUE THREAD

**Issue by flancast90** [flancast90/Speech-To-Text-in-TW5#9]
Just need a one-liner solution to get the language of TW (not plugin), TW itself. I am going to implement an option to change the plugin language when TW language changes.

**Comment by BurningTreeC** [comment]
Hi @flancast90 , the language is stored in the tiddler `$:/language`
you can get its content by `$tw.wiki.getTiddlerText("$:/language");`

**Comment by BurningTreeC** [comment]
I wouldn't change the language of the recognition when the tiddlywiki language changes

**Comment by flancast90** [comment]
I intend to make it an option. I'll add the function now in JS, and let you do the TW side of things. I'm thinking we should add a settings page where the user can opt-in/out of things such as this, some different commands, etc.

**Comment by BurningTreeC** [comment]
Yes @flancast90 that's a good idea

**Comment by flancast90** [comment]
Auto-change lang is a go! when the user opts in, just change the var ``autochange_lang = true``, and my JS code will do the rest! Just ran a few tests for it!

**Comment by flancast90** [comment]
Your updates look good. Perhaps we should add an option in the Settings>Speech-to-Text to change language when TW language changes?

**Comment by BurningTreeC** [comment]
>Your updates look good. Perhaps we should add an option in the Settings>Speech-to-Text to change language when TW language changes?

Yes @flancast90 , I'll add that option. I forgot about that

**Comment by BurningTreeC** [comment]
The problem now is, that we have 3 methods to switch language, which makes the handling of the various states much more complicated

**Comment by BurningTreeC** [comment]
I'm closing this issue since it's implemented. Thanks @flancast90 :)
